/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/hello_screen` | `/hello_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/recovery_password` | `/recovery_password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/registration` | `/registration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/like` | `/like`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/user_profile` | `/user_profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/hello_screen` | `/hello_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/recovery_password` | `/recovery_password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/registration` | `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/library` | `/library`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/like` | `/like`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/user_profile` | `/user_profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/hello_screen${`?${string}` | `#${string}` | ''}` | `/hello_screen${`?${string}` | `#${string}` | ''}` | `${'/(login)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/recovery_password${`?${string}` | `#${string}` | ''}` | `/recovery_password${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/registration${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/like${`?${string}` | `#${string}` | ''}` | `/like${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/user_profile${`?${string}` | `#${string}` | ''}` | `/user_profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/hello_screen` | `/hello_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/recovery_password` | `/recovery_password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/registration` | `/registration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/like` | `/like`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/user_profile` | `/user_profile`; params?: Router.UnknownInputParams; };
    }
  }
}
